services:
    newscoop_solrsearch_plugin.lifecyclesubscriber:
        class: Newscoop\SolrSearchPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    index_client.solr:
        class: "Newscoop\SolrSearchPluginBundle\Search\SolrIndexClient"
        arguments:
            - @service_container

    newscoop_solrsearch_plugin.query_service:
        class: Newscoop\SolrSearchPluginBundle\Services\SolrQueryService
        arguments:
            - @service_container
